core/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("about/", views.about_view, name="about"),
    path("contacts/", views.contacts_view, name="contacts"),
    path("categories/<slug:slug>/", views.category_detail_view, name="category_detail"),
    path("products/<slug:product_slug>/", views.product_view, name="product_detail"),
    path("cart/", views.basket_view, name="cart"),
    path('users/register/', views.user_registration, name="register"),
    path('users/login/', views.user_login, name="login"),
    path('users/logout/', views.user_logout, name="logout"),
    path("to_cart/<int:product_id>/<str:action>/", views.to_cart, name="to_cart"),
    path("send_email/", views.send_phone_number_to_telegram, name="send_email"),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("__debug__/", include("debug_toolbar.urls")),

    path("", include("app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.templatetags.static import static
from django.urls import reverse

from .managers import CustomUserManager
from helpers.functions import convert_price, format_price


class CustomUser(AbstractUser):
    username = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.CharField(verbose_name="Номер телефона", max_length=15)
    email = models.EmailField(unique=False, default="")

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def get_name_by_email(self):
        return str(self.email).split("@")[0]

    class Meta:
        verbose_name = "Пользовать"
        verbose_name_plural = "Пользователи"
        ordering = ["email"]


class Category(models.Model):
    name = models.CharField(verbose_name="Категория", max_length=155)
    slug = models.SlugField(verbose_name="Слаг", default="")
    show_on_homepage = models.BooleanField(
        verbose_name="Показывать на главной странице",
        default=False,
        help_text="При выборе, добавит все товары данной категории на главную страницу.",
    )
    show_as_bestseller = models.BooleanField(
        verbose_name="Сделать самым продоваемым",
        default=False,
        help_text="При выборе, добавит все товары данной категории на главную в раздел самых продоваемых товаров",
    )

    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"slug": self.slug})

    def get_category_products_count(self):
        products = self.categories.all()
        return products.count()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Product(models.Model):
    SIZE_CHOICES = [(f"{i} мм", f"{i} мм") for i in range(1, 30)]

    QUANTITY_CHOICES = [(i, i) for i in range(1, 30)]
    CORNICE_TYPE_CHOICES = [
        ("Алюминевый", "Алюминевый"),
        ("Пластиковый", "Пластиковый"),
    ]

    CONTROL_TYPE_CHOICES = [
        ("Ручной", "Ручной"),
        ("С электроприводом", "С электроприводом"),
    ]

    name = models.CharField(verbose_name="Название товара", unique=True, max_length=155)
    width = models.CharField(verbose_name="Ширина", max_length=15, choices=SIZE_CHOICES)
    height = models.CharField(
        verbose_name="Высота",
        max_length=15,
        choices=SIZE_CHOICES,
    )
    is_left_control = models.BooleanField(
        verbose_name="Управление слева?",
        default=False,
        blank=True,
    )
    is_right_control = models.BooleanField(
        verbose_name="Управление Справа?",
        default=False,
        blank=True,
    )
    quantity = models.IntegerField(verbose_name="Количество", choices=QUANTITY_CHOICES)
    cornice_type = models.CharField(
        verbose_name="Тип карниза",
        blank=True,
        choices=CORNICE_TYPE_CHOICES,
        max_length=50,
    )
    control_type = models.CharField(
        verbose_name="Тип управления",
        blank=True,
        choices=CONTROL_TYPE_CHOICES,
        max_length=50,
    )
    manufacturer_country = models.CharField(
        verbose_name="Страна производитель",
        max_length=150,
    )
    fabric_type = models.CharField(verbose_name="Тип ткани", max_length=150)
    property = models.CharField(verbose_name="Свойство", max_length=100)
    dimming = models.SmallIntegerField(verbose_name="Затемнение", default=0)
    price = models.SmallIntegerField(verbose_name="Цена у.е", default=0)
    converted_price = models.IntegerField(
        verbose_name="Сконвертированная цена",
        blank=True,
        null=True,
        help_text="Данное поле заполнять не нужно, при вводе цены в долларах и сохранении продукта, цена будет добавлена сама",
    )
    description = models.TextField(verbose_name="Описание продукта")
    category = models.ForeignKey(
        Category,
        verbose_name="Категория",
        on_delete=models.CASCADE,
        related_name="categories",
        default=None,
    )
    slug = models.SlugField(default="")
    created_at = models.DateTimeField(
        verbose_name="Дата добавления",
        auto_now_add=True,
        null=True,
    )
    color = models.CharField(verbose_name="Цвет", max_length=100, default="")
    discount = models.IntegerField(verbose_name="Размер скидки", blank=True, null=True)

    def save(self, *args, **kwargs):
        self.converted_price = convert_price(self.price)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"product_slug": self.slug})

    def get_first_photo(self):
        images = self.images.all()
        if not images:
            return static("images/soon.png")
        return images[0].photo.url

    def get_choices_range(self):
        return [choice[0] for choice in self.SIZE_CHOICES]

    def get_quantity_range(self):
        return [choice[0] for choice in self.QUANTITY_CHOICES]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class ProductOption(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_options"
    )
    option_main = models.CharField(
        verbose_name="Главная характеристика", max_length=200
    )
    option_additional = models.TextField(verbose_name="Описание характеристики")

    def __str__(self):
        return f"{self.product}: {self.option_main}"

    class Meta:
        verbose_name = "Характеристика"
        verbose_name_plural = "Характеристики"


class ProductImage(models.Model):
    def make_folder_path(self, filename):
        return f"photos/products/{filename}"

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="images"
    )
    photo = models.ImageField(verbose_name="Фото", upload_to=make_folder_path)

    class Meta:
        verbose_name = "Фотография"
        verbose_name_plural = "Фотографии"


class ProjectsGallery(models.Model):
    title = models.CharField(verbose_name="Заголовок проекта", max_length=255)
    subtitle = models.CharField(verbose_name="Подзаголовок проекта", max_length=255)
    photo = models.ImageField(
        verbose_name="Фото проекта", upload_to="gallery/projects/", default=""
    )

    def __str__(self):
        return f"{self.title}: {self.subtitle}"

    class Meta:
        verbose_name = "Проект"
        verbose_name_plural = "Галерея проектов"


class Client(models.Model):
    name = models.CharField(verbose_name="Название клиента", max_length=255)
    photo = models.ImageField(verbose_name="Логотип клиента", upload_to="clients/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"


class Comment(models.Model):
    author = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="comments"
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="comments"
    )
    body = models.TextField(verbose_name="Текст комментария")

    def __str__(self):
        return f"{self.author}: {self.product}"

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class CommentItem(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    img = models.ImageField(
        verbose_name="Фото", upload_to="comments/", blank=True, null=True
    )


class Customer(models.Model):
    user = models.OneToOneField(
        CustomUser, on_delete=models.SET_NULL, blank=True, null=True
    )
    first_name = models.CharField(verbose_name="Имя", max_length=150)
    last_name = models.CharField(verbose_name="Фамилия", max_length=150)
    email = models.EmailField(verbose_name="Почта")
    phone_number = models.CharField(verbose_name="Номер телефона", max_length=15)
    mounting_type = models.CharField(verbose_name="Тип монтажа", max_length=255)
    address = models.CharField(verbose_name="Адрес", max_length=255)
    comment = models.CharField(verbose_name="Комментарий", max_length=1000, default="")
    delivery_type = models.CharField(verbose_name="Тип доставки", max_length=150)
    delivery_option = models.CharField(
        verbose_name="Вариант доставки",
        max_length=150,
        default="",
    )

    def __str__(self):
        return self.first_name


class Order(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)

    @property
    def get_cart_total_price(self):
        order_products = self.orderproduct_set.all()
        total = sum([item.get_total_price for item in order_products])
        return format_price(total)

    @property
    def get_cart_total_quantity(self):
        order_products = self.orderproduct_set.all()
        return sum([item.quantity for item in order_products])


class OrderProduct(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, null=True, related_name="order_products"
    )
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0)
    added_at = models.DateTimeField(auto_now_add=True)

    @property
    def get_total_price(self):
        return int(self.product.converted_price) * self.quantity


class Feedback(models.Model):
    body = models.TextField(verbose_name="Текст отзыва")
    feedback_author = models.CharField(verbose_name="Имя автора отзыва", max_length=255)
    author_company = models.CharField(
        verbose_name="Компания автора отзыва", max_length=255
    )
    avatar = models.ImageField(
        verbose_name="Фото автора отзыва", upload_to="feedback/author/"
    )

    def __str__(self):

core/app/templates/app/components/product/_comments.html
{% load static %}

<section class="single-comments">
    <h3 class="single-comments__title">Комментарии</h3>
    {% if request.user.is_authenticated %}
        <div class="single-comments__content">
            <form class="single-comments__form" action="" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="single-comments__user">
                    <strong class="single-comments__fullname">{{ request.user.email }}</strong>
                </div>
                <textarea name="body" cols="" rows="" class="single-comments__textarea"
                          placeholder="Оставьте комментарий" required="" id="id_body"></textarea>

                <p style="margin: 15px 0;">Прикрепите фотографию нашей работы</p>

                <input type="file" name="img" multiple="" accept="image/*" id="id_img">
                <button class="single-comments__btn darkBlueHover">Отправить</button>
            </form>
            <div class="single-comments__block">
                {% for comment in comments %}
                    <div class="single-comments__item">
                        <div class="single-comments__user">
                            <strong class="single-comments__fullname">{{ comment.author.email }}</strong>
                        </div>
                        <p class="single-comments__descr">{{ comment.body }}</p>


                        <div class="single-comments__photos">
                            {% for comment_item in comment.commentitem_set.all %}
                                <div class="single-comments__photo">
                                    <img src="{{ comment_item.img.url }}" alt="">
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
{#            {{  }}#}
            {% if comments|length < comments_total %}
                <a class="single-comments__loadmore" href="?next={{ comments|length }}">Загрузить еще</a>
            {% endif %}
        </div>

    {% else %}
        <p>Только зарегистрированные пользователи могут оставлять комментарии</p>
    {% endif %}
</section>

core/app/templates/app/components/product/_single-content.html
{% load custom_tags %}

{% convert_price product.converted_price as product_price %}

<div class="single__content">
    <ul class="single__content-features">
        <li class="single__content-elem">Страна производитель: {{ product.manufacturer_country }}</li>
        <li class="single__content-elem">Тип ткани: {{ product.fabric_type }}</li>
        <li class="single__content-elem">Свойство: {{ product.property }}</li>
        <li class="single__content-elem">Затемнение: {{ product.dimming }}%</li>
    </ul>
    <h4 class="single__content-price">Цена: {{ product_price }} сум за 1 м2</h4>
    <p class="single__content-info">{{ product.description }}</p>
    <h3 class="single__content-characters">Характеристики</h3>

    {% for option in product.product_options.all %}
    <div class="single__content-item">
        <h4 class="single__content-title">{{ option.option_main }}</h4>
        <p class="single__content-descr">{{ option.option_additional }}</p>
    </div>
    {% endfor %}

</div>

core/app/templates/app/components/product/_single-good.html
{% load static %}

<div class="single__good">
    <div class="single__left">
        <div class="single__left-images">
            {% for img in product.images.all %}
            <div class="single__left-item">
                <img src="{{ img.photo.url }}" alt="">
            </div>
            {% endfor %}
        </div>
        <div class="single__left-show" data-img="{{ product.get_first_photo }}">
            <div class="single__left-zoom" itemprop="image"></div>
            <img src="{{ product.get_first_photo }}" alt=""></div>
    </div>

    <form class="single__right" method="post" action="{% url 'to_cart' product.pk 'add' %}">
        {% csrf_token %}
        <h2 class="single__right-title">{{ product.name }}</h2>
        <strong class="single__right-feature size">Размер</strong>
        <div class="single__right-sep size">
            <div class="single__right-chose">
                <div class="single__right-hint-abs"><p>Менее 1 кв.м, считается как 1 кв.м</p></div>
                <span class="single__right-info">ширина</span>

                <select class="single__right-select" name="item-width">
                    <option value="{{ product.get_choices_range.0 }}" selected="selected">
                        {{ product.get_choices_range.0 }}
                    </option>
                    {% for choice in product.get_choices_range %}
                    <option value="{{ choice }}">{{ choice }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="single__right-chose">
                <div class="single__right-hint-abs"><p>Менее 1 кв.м, считается как 1 кв.м</p></div>
                <span class="single__right-info">Длина</span>
                <select class="single__right-select" name="item-length">
                    <option value="{{ product.get_choices_range.0 }}" selected="selected">
                        {{ product.get_choices_range.0 }}
                    </option>
                    {% for choice in product.get_choices_range %}
                    <option value="{{ choice }}">{{ choice }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <strong class="single__right-feature control">Управление</strong>
        <div class="single__right-sep control">
            <label class="single__right-label">
                <input type="radio" value="left" name="item-control">
                <span class="single__right-check"></span>
                <span class="single__right-info">Слева</span>
            </label>
            <label class="single__right-label">
                <input type="radio" value="right" name="item-control">
                <span class="single__right-check"></span>
                <span class="single__right-info">Справа</span>
            </label>
        </div>
        <strong class="single__right-feature count">Кол-во</strong>
        <div class="single__right-sep count">
            <select class="single__right-select" name="item-count">
                {% for item in product.get_quantity_range %}
                <option value="{{ item }}">{{ item }}</option>
                {% endfor %}
            </select>
            <span class="single__right-info">штук</span>

        </div>
        <div class="single__right-flex">
            <div class="single__right-flex-left">
                <strong class="single__right-feature type-cornise">Тип карниза</strong>
                <div class="single__right-sep">
                    <label class="single__right-label">
                        <input type="radio" value="aluminium" name="item-cornice-type">
                        <span class="single__right-check"></span>
                        <span class="single__right-info">Алюминевый</span>
                    </label>
                    <label class="single__right-label">
                        <input type="radio" value="plastic" name="item-cornice-type">
                        <span class="single__right-check"></span>
                        <span class="single__right-info">Пластиковый</span>
                    </label>
                </div>
                <strong class="single__right-feature type-control">Тип управления</strong>
                <div class="single__right-sep">
                    <label class="single__right-label">
                        <input type="radio" value="manual" name="item-control-type">
                        <span class="single__right-check"></span>
                        <span class="single__right-info">Ручной</span>
                    </label>
                    <label class="single__right-label">
                        <input type="radio" value="electro" name="item-control-type">
                        <span class="single__right-check"></span>
                        <span class="single__right-info">С электроприводом</span>
                    </label>
                </div>
            </div>
            <button class="single__right-btn darkBlueHover" type="submit">
                <strong>В корзину</strong>
                <span class="single__right-icon">
                    <img src="{% static 'images/icons/work-light.svg' %}" alt="">
                </span>
            </button>
        </div>
    </form>
</div>